### ISSUE TITLE
Context menu for custom command blocks

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1135]
![image](https://user-images.githubusercontent.com/13686399/31515885-a6730f20-af4b-11e7-997f-c63e2a0b2aa5.png)

6 options, in order:
- [x] duplicate
- [x] delete
- [ ] add comment (tracked in #1120)
- [x] help
- [x] edit (tracked in https://github.com/LLK/scratch-blocks/issues/607)
- [x] define (tracked in https://github.com/LLK/scratch-blocks/issues/1136)

**Comment by rachel-fenichel** [comment]
#1137 added all options except for comments.
