### ISSUE TITLE
Comments ToDo

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1554]
Making one giant Issue for the separate comment tasks that still remain:

- [x] Workspace comments need to be updated to look/work like block comments: Fixed with #1575 
    - [x] Size of comment text
    - [x] Font used for comment text
    - [x] Size of top bar
    - [x] Minimize icon and functionality
    - [x] Delete icon and functionality
- [ ] Some outstanding issues with drag + text selection - Tracking in #1623
- [ ] Auto layout of block comments needs improvement - Tracking in #1624
    - [ ] Block comments render too far away from blocks in wide stacks
- [x] Workspace does not scroll with block comments (e.g. if a block comment gets created or dragged far off, can't scroll the workspace to it) Fixed with #1557
- [ ] Cannot scroll workspace if mouse happens to be over a block comment - Tracking in #1625
- [x] Workspace scroll is wonky if block comments are on the screen. Scroll gets pinned to a corner of the workspace. Fixed with #1587
- [ ] Comment rendering needs improvement - Tracking in #1626
- [ ] Delete block comments by dragging to the toolbox - Tracking in #1627
- [ ] Block comment bubble dragging does not work in RTL - Tracking in google/blockly#1896
- [x] Persist comment state Fixed with #1557
    - [x] Add events to block comments
    - [x] Undo/redo
    - [x] Add event listeners for block and workspace comments in scratch-vm (Fixed with LLK/scratch-vm#1191
    - [x] Modify CommentChange event to track changes in minimized state
    - [x] Track resizing changes through events
- [ ] Comment anchor point is off for custom procedure definition block - Tracking in #1628
- [ ] Allow dragging block comment from middle of comment (like workspace comments) - Tracking in #1629
- [ ] Need minimum resizing dimensions for comments - Tracking in #1630
- [ ] Cannot edit the text of a comment on touch devices - Tracking in #1631
- [x] Comments overlap each other: Fixed with #1589
![overlapping comments](https://user-images.githubusercontent.com/1786240/41428384-f1b3bd34-6fd7-11e8-883d-c2120649fbf9.gif)
![image 2](https://user-images.githubusercontent.com/1786240/41428414-0bbf41da-6fd8-11e8-9642-a6cb77dea34e.png)

**Comment by rachel-fenichel** [comment]
Related to "Cannot scroll workspace if mouse happens to be over a block comment": You probably can't scroll comment contents.  I think that's fine, since you can resize them, but it's worth knowing.

**Comment by paulkaplan** [comment]
@kchadha not sure if this is listed there, or if you'd prefer it in another issue, but 
![overlapping comments](https://user-images.githubusercontent.com/654102/41428084-0487bf56-6fd7-11e8-9c13-70a8a882aea7.gif)

**Comment by BryceLTaylor** [comment]
block comment focus issue: https://github.com/LLK/scratch-blocks/issues/1601

**Comment by BryceLTaylor** [comment]
This gif has many things wrong with it:
![blockcommentscroll](https://user-images.githubusercontent.com/1088291/41676444-805641be-7493-11e8-8b8f-b310463470e3.gif)

1. After resizing and switching to a different sprite and back the comment moves in relation to the block
2. When shrinking the comment it ends scrolled to the top.  After switching to another sprite and back it's scrolled to the bottom (probably related to the focus issue in #1601).  Then when you move the comment it scrolls to the top again.  It should likely pick a place to be scrolled to and stay there.

**Comment by kchadha** [comment]
Closing this issue as all the remaining (no checkbox) tasks are being tracked in separate issues.
