### ISSUE TITLE
Tracking issue for vertical rendering to spec

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#259]
Match design from #3. This includes:
- [x]  Add one of each of those block types to blocks_vertical so we know what we're up against.
- [x]  Fix actual sizing of blocks (they are larger in spec - to be zoomed down for desktop)
- [x]  Fix corner radii on most blocks
- [x]  Adding a notch to the bottom of statement inputs (bays/holes for blocks)
- [x]  Make notch using Bezier curves (see #93 for reference - these should be turned on their side for vertical)
- [x] Fix font sizes to match spec
- [x] Don't draw holes for shadow blocks in the parent block
- [ ] Draw field chrome for shadow blocks:
  - [x] field_number-type chrome (lots of corner radius)
  - [x] field_text-type chrome (less corner radius)
  - [ ] drop-down-type chrome
  - [x] boolean-type chrome
- [x] Rendering of reporter-type blocks. Blocks with no next, no previous connections, and an output should render as reporters. The shape of the block depends on output type (either boolean-type with angle corners or value-type with rounded corners).
- [x] Center alignment of text (might get this for free if https://github.com/google/blockly/issues/333 is implemented in upstream)
- [x] Fixing the hat block shape to spec
- [ ] Alignment of fields horizontally (LEFT/RIGHT/CENTER)
- [x] Minimum positioning of second field (see: if, "say" examples), only if there is a previous connection.
- [x] C-blocks have different minimum width
- [x] Need to make size of C-block bottoms always match top. I.e., the width of all rows should match the maximum width of a single row...

**Comment by tmickel** [comment]
- [ ] Need to make size of C-block bottoms always match top

**Comment by tmickel** [comment]
400%
![r3_vert-block-sketches](https://cloud.githubusercontent.com/assets/120403/15549159/6034fe34-2279-11e6-9be9-4e397667f89d.png)

**Comment by tmickel** [comment]
- [ ] Minimum positioning of second field (see: if, "say" examples), only if there is a previous connection.
- [ ] C-blocks have different minimum width

**Comment by tmickel** [comment]
- [ ] Alignment of fields horizontally (LEFT/RIGHT/CENTER)

**Comment by tmickel** [comment]
Closing and making a couple of new issues.
